version: 0.2
phases:
  pre_build:
    commands:
      - echo "criando pasta de build da layer"
      - mkdir gmail-lambda-layer
      - mkdir gmail-lambda-layer/nodejs
      - cp functions.js ./gmail-lambda-layer/nodejs/functions.js
      - cp package-lock.json ./gmail-lambda-layer/nodejs/package-lock.json
      - cp package.json ./gmail-lambda-layer/nodejs/package.json
      - cd gmail-lambda-layer/nodejs
      - npm install
  build:
    commands:
      - echo "faz o build da lambda"
      - cd ..
      - zip -r gmail-lambda-layer.zip .
      - aws lambda publish-layer-version --layer-name $LAMBDA_LAYER_NAME --zip-file fileb://gmail-lambda-layer.zip --compatible-runtimes $LAMBDA_LAYER_RUNTIME
artifacts:
  discard-paths: yes